### PR TITLE
Allow config to be dumped to json file

### PR DESCRIPTION
**Pull request by Yethal**
I'll accept any tips&tricks on this one, I'm still learning Nix
Necessary for https://github.com/nix-community/disko/issues/789

Tested via following script:
```
#!/usr/bin/env nu
ls example
| where type == file
| update name {path expand}
| par-each {|example|
    let dir_name = ('configs'|path join ($example.name|path parse|get stem))
    mkdir $dir_name
    let store_path = (nix-build ./cli.nix --argstr mode config --no-out-link --arg diskoFile $example.name)
        cp $store_path $dir_name
}
```

### CODE REVIEW

**Comment by Yethal** [comment]
@phaer

**Comment by iFreilicht** [comment]
You can already do this with any disko configuration with the following command:

```
nix eval --json -f example/boot-raid1.nix
```

**Comment by Yethal** [comment]
Will it end up in the store where the new(?) improved(?) disko script will be able to read it? The design discussed under https://github.com/nix-community/disko/issues/789 assumes a script that accepts the entire disko config as a json file

**Comment by iFreilicht** [comment]
> Will it end up in the store where the new(?) improved(?) disko script will be able to read it? The design discussed under https://github.com/nix-community/disko/issues/789 assumes a script that accepts the entire disko config as a json file

No, but it doesn't need to as far as I see it. There are basically two cases for where the  configuration can come from: a bare nix file which can be evaluated on its own, or a flake.
For the deployment scenario, we have local execution or a remote deployment with nixos-anywhere.

When you deploy with nixos-anywhere, you always send over the full configuration (including the disko config) to the target's store and build there. The same happens when you use a flake, even on a local deployment. Only when running disko locally with a bare `.nix` file will the config not end up in the store, but it doesn't need to, because you can evaluate it directly.

In all these cases, the program (I don't want to call it a script) will have to do the following things:

1. `nix eval --json` (probably with an intermediate nix file that injects function arguments if required, like `cli.nix` does now) to ingest the configuration
2. Transform it into a representation of the **desired** state the drives should have
3. Inform the user about any logical errors in that configuration (e.g. raid1 with only one drive)
3. Probe the OS and create the same representation of the **current** state the drives have
4. Generate a diff of sorts that shows what steps have to be taken to turn the **current** state into the **desired** state
5. Tell the user what these steps are and ask for confirmation*
6. Execute as many of these steps as possible
7. Comprehensively explain what went wrong and why

*the UX for this has not been decided. For sure there will have to be a flag to allow for an unattended installation, and it would be nice if the user could interactively decide which steps to take, but that's a stretch goal.

Maybe this explanation should go into the main thread.

One thing that is very important here is that we do NOT want to use nix as a templating engine to generate this program. The program's **behavior** should be a function of the configuration, not the **program itself**.

> Also, `nix-eval --json` fails if a given disko config is a function not an attrset (i.e example/luks-on-mdadm.nix)

True, for these configs you'll need to do something more sophisticated, like[ `cli.nix` already does](https://github.com/nix-community/disko/blob/d39ee334984fcdae6244f5a8e6ab857479cbaefe/cli.nix#L53C1-L56C19).

**Comment by Yethal** [comment]
So nix would perform steps 1-3 and if no errors are present it would generate a plan (in the form of json) that would then be fed to the program. Steps 4-8 would be executed by the program with no nix involvement.
If that's how the concerns should be separated then how should this PR be adjusted? Or is it even needed at all?

I can do the program part of this but need help/guidance in regards to Nix side of the process.

btw, steps 4-8 look a lot like how Terraform works but with local resources instead of remote.

**Comment by iFreilicht** [comment]
> So nix would perform steps 1-3 and if no errors are present it would generate a plan (in the form of json) that would then be fed to the program. Steps 4-8 would be executed by the program with no nix involvement.

No, not even that. Nix will only do step 1. Everything else is handled by the program, even step 3 (which currently is done by nix). We have quite a few issues with validating the config that are very difficult if not impossible to solve in nix.

Well, the only exception is things that influence the NixOS configuration, but that is implemented already, so we don't need to worry about it for this.

> I can do the program part of this but need help/guidance in regards to Nix side of the process.

My suggestion would be to not worry about disko configs that are functions for now, only those that can be evaluated easily by a call to `nix eval`. I also started working on this (though I don't have much time right now, so please don't let that stop you), and the best approach for prototyping this is to write a disko config for your current system eval it, and then try to implement step 3 and 4 until both reach the same result.

If you need additional help, feel free to add me on matrix (@ifreilicht:matrix.org) or DM me on the NixOS discourse :)

> btw, steps 4-8 look a lot like how Terraform works but with local resources instead of remote.

Jup, that's where I got the idea from. I think the biggest difference will be that we don't store the current state but regenerate it, and how step 6 will be presented, but the general concept is indeed the same.

> If that's how the concerns should be separated then how should this PR be adjusted? Or is it even needed at all?

I don't think it's needed. I'll close it :)

**Pull request closed without merging**
