### PR TITLE
feat(luks): Add settings submodule

### PR DESCRIPTION
**Pull request by rogarb**
This mirrors the NixOS boot.initrd.luks.devices.<name>.keyFileOffset and boot.initrd.luks.devices.<name>.keyFileSize options.

### CODE REVIEW

**Comment by Lassulus** [comment]
How about we add a settings key to the luks type which would be passed to boot.initrd.luks.devices.${config.name} ? Not sure if we want to replicate all the options in disko.

**Comment by Lassulus** [comment]
we could still get them from settings.keyFileSize in the create/mount script? we would get the type checks only when evaluating the config though. but that seems only important for people not using the config output of disko? 

So I'm not sure, I guess I would prefer having all the settings of nixpkgs inside one attribute?

**Comment by rogarb** [comment]
Sorry I got confused about your proposal. I think that I have understood what you mean now, I think it is definitely a good idea. I will try to come up with an implementation.

**Comment by rogarb** [comment]
@Lassulus it seems that I can't get to implement the `settings` option as a submodule properly, would you have any suggestion for a proper way to do it?

**Comment by Lassulus** [comment]
ah yeah, I will push to your branch shortly. basically you can skip defining a type since we silently reuse the nixpkgs type.

**Comment by Lassulus** [comment]
for backwards compatibility I suggest we keep keyFile in the luks type and trace a deprecation warning when it is used.

**Comment by rogarb** [comment]
I added back the keyFile option with a warning message. I guess that the PR is now ready to be merged.

**Comment by Lassulus** [comment]
@mergify queue

**Pull request merged**
