### PR TITLE
Add reiserfs utils for formatting

### PR DESCRIPTION
**Pull request by tolbrino**

### CODE REVIEW

**Comment by iFreilicht** [comment]
Thank you for your contribution! Could you also add an example (similar to https://github.com/nix-community/disko/blob/master/example/f2fs.nix) and a test (similar to https://github.com/nix-community/disko/blob/master/tests/f2fs.nix)?

Having a known-good example like helps a lot when people report issues.

**Comment by Mic92** [comment]
Is this not queued for removal in the linux kernel? https://en.wikipedia.org/wiki/ReiserFS

**Comment by tolbrino** [comment]
> Thank you for your contribution! Could you also add an example (similar to https://github.com/nix-community/disko/blob/master/example/f2fs.nix) and a test (similar to https://github.com/nix-community/disko/blob/master/tests/f2fs.nix)?
> 
> Having a known-good example like helps a lot when people report issues.

Thanks for the hint, I added the example and test.

**Comment by tolbrino** [comment]
> Is this not queued for removal in the linux kernel? https://en.wikipedia.org/wiki/ReiserFS

Correct, but previous kernel versions are supported until 2026 EOY.

**Comment by Mic92** [comment]
vm-test-run-disko-reiserfs> machine # mkfs.reiserfs 3.6.27
vm-test-run-disko-reiserfs> machine # 
vm-test-run-disko-reiserfs> machine # ATTENTION: YOU SHOULD REBOOT AFTER FDISK!
vm-test-run-disko-reiserfs> machine #   ALL DATA WILL BE LOST ON '/dev/disk/by-partlabel/disk-main-root'!
vm-test-run-disko-reiserfs> machine # Continue (y/n):[   13.898827] dhcpcd[673]: eth0: leased 10.0.2.15 for 86400 seconds

Looks like it wants a confirmation prompt? Maybe there is a flag to always say "yes".

**Comment by K900** [comment]
You know reiserfs is getting removed upstream, right?

**Comment by Mic92** [comment]
> Is this not queued for removal in the linux kernel? https://en.wikipedia.org/wiki/ReiserFS

Yes.

**Comment by Mic92** [comment]
> > Is this not queued for removal in the linux kernel? https://en.wikipedia.org/wiki/ReiserFS
> 
> Correct, but previous kernel versions are supported until 2026 EOY.

Not sure this is worth it actually. This is a bit more than a year.

**Comment by tolbrino** [comment]
> > > Is this not queued for removal in the linux kernel? https://en.wikipedia.org/wiki/ReiserFS
> > 
> > 
> > Correct, but previous kernel versions are supported until 2026 EOY.
> 
> Not sure this is worth it actually. This is a bit more than a year.

This is 2.25 years actually. I actually updated the branch to have the test working.

**Comment by piegamesde** [comment]
either way, this PR lacks a clear motivation

**Comment by tolbrino** [comment]
Its perfectly fine if this change isn't included upstream, I can keep it in my fork. Thanks for the quick turnaround.

**Pull request closed without merging**
