### PR TITLE
fix option type in `mkHook`

### PR DESCRIPTION
**Pull request by name-snrl**
#679

### CODE REVIEW

**Comment by name-snrl** [comment]
@Mic92 I tried adding indentation, but it doesn't help, any ideas?

```
  )
  
  
  zfs snapshot -r zroot/aleria@blank
zfs snapshot zroot/rootfs@blank
)
```

**Comment by Mic92** [comment]
Here is the implementation of indent:

```
indent = replaceStrings [ "\n" ] [ "\n  " ];
```

In a nix repl it looks like it should work:

```
nix-repl> lib.replaceStrings [ "\n" ] [ "\n  " ] ''
          foo
          bar
          ''
"foo\n  bar\n  "
```

**Comment by Mic92** [comment]
However I wouldn't consider this a blocker of this pull request.

**Comment by name-snrl** [comment]
> like it should work

Yeah, but it didn't(

> However I wouldn't consider this a blocker of this pull request.

Alright, I still have some free time today to investigate. I'll let you know when it's ready to merge.

**Comment by name-snrl** [comment]
> it doesn't help

It was my bad, I think I opened an old file or something. PR ready to merge.

@Mic92

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
