### PR TITLE
cleanup host environment passed to VM for image building

### PR DESCRIPTION
**Pull request by pedohorse**
keeping only `origBuilder` env from host

should resolve https://github.com/nix-community/disko/issues/622

### CODE REVIEW

**Comment by Mic92** [comment]
Looks good. Does it work?

**Comment by pedohorse** [comment]
i've mentioned in the issue https://github.com/nix-community/disko/issues/622 that it does seem to work fine, but i only manually tested a few configs for `config.system.build.diskoImagesScript`, and visually confirmed that result boots and seems good, nothing else.

the change _should_ affect only VM environment, created early in stage-2 script, the only change in environment in which the script that starts VM is executed is the absence of `origBuilder` var there, as it's set through `preVM` instead

i basically know two features in this project so far :)
are there any automated tests to ensure nothing else broke from this change?

**Comment by Lassulus** [comment]
there are tests in the tests folder, they should be nix-build able or alternatively with nix build .#tests.make-disk-image

**Comment by pedohorse** [comment]
i've ran some tests so far (I assume - the process of building IS running the test), it seem to work fine.
interestingly, the tests run with `nix build` will run in clean environment, so they won't catch issues as with running the result of image building script in tainted user enviornment. (unless there is such special test case that imitates that problem somewhere, but I doubt that since it seems that this was not noticed to be something noticeable before)

Oh wait, (i'm blind) I've just noticed that there are github actions that run all the tests, and all the tests pass

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
