### PR TITLE
btrfs multi-device raid capability support

### PR DESCRIPTION
**Pull request by stephenandary**
Pertaining to https://github.com/nix-community/disko/issues/261. 

Starting to think through how multi-device raid can be done easily for btrfs file systems. 

Raid 5/6 should not be supported, as they are unstable. Profiles can be seen [here](https://btrfs.readthedocs.io/en/latest/mkfs.btrfs.html#profiles)

I think the solution may be optimal if we can accept a list of mount devices, and pass in raid options through extraArgs to align with commands like:

`mkfs.btrfs -m raid10 -d raid10 /dev/sdb /dev/sdc /dev/sdd /dev/sde`

PR is not complete - just started so I can look at it after holiday.

I will revert formatting in PR eventually. Just don't feel like it at the moment.

### CODE REVIEW

**Comment by stephenandary** [comment]
TODO: See `lib/default.nix`, there is a reference to a devices list which maps an attribute set based on device name and mount point. Can/should this be used in btrfs extraDevices option, or should I just update device option to use devices if possible?

**Comment by Mic92** [comment]
It's also ok to introduce new types for btrfs raids, if it doesn't fit the current type.

**Comment by stephenandary** [comment]
BTFRS raid is parity raid, and should be considered different than lvm raid, so that would make sense. 

I put a pin in this because I am not sure how disko partitions, formats, and works with fstab for uuid's yet, and it is easier to reason about in bash and rust for me

I can take a bit of time to look at it today though.

**Comment by stephenandary** [comment]
@Mic92 

I think the best option here will be to close or rename this PR, and to add an example where one can pass [add](https://btrfs.readthedocs.io/en/latest/btrfs-device.html#add-new-device) and [balance](https://btrfs.readthedocs.io/en/latest/Balance.html) commands like `btrfs device add` and  `btrfs balance start -v -mconvert=raid1C4,soft -dconvert=raid10,soft mnt/` after the disks are formatted and mounted.

To implement this in btrfs.nix, you would need to ensure that swap was not defined within a btrfs partition for multidisk btrfs, because it is not supported yet. You would also need to warn or restrict about raid56 being unstable potentially. 

Is it possible for Disko to run btrfs `add` and `balance` commands after mounting? Because I think that would be lightest lift for refactor, and could potentially be done in an example with extra args or something.

**Comment by stephenandary** [comment]
An example of why I say this may be challenging to refactor currently: 

```sh
# PARTITIONING

# primary disk
parted -s /dev/nvme0n1 -- mklabel gpt \
    mkpart ESP fat32 1MB 512MB \
    mkpart root btrfs 512MB -8GB \
    mkpart swap linux-swap -8GB 100% \
    set 3 esp on

# raid disks
parted --script /dev/nvme1n1 -- mklabel gpt \
    mkpart primary btrfs 0% 100% \

parted --script /dev/nvme2n1 -- mklabel gpt \
    mkpart primary btrfs 0% 100% \
    
# FORMATTING

# format boot
uuid_8=$(uuidgen | tr '[:lower:]' '[:upper:]' | head -c8) # lower case labels don't work on all systems
boot_uuid=(${uuid_8:0:4}-${uuid_8:4:9})
mkfs.fat -F 32 -n boot -i $uuid_8 /dev/nvme0n1p1

# format multidisk btrfs
btrfs_uuid=$(uuidgen)
mkfs.btrfs -f -L nixos -U $btrfs_uuid -d raid1c3 -m raid1c3 /dev/nvme0n1p2 /dev/nvme1n1p1 /dev/nvme2n1p1

# format swap - currently limitations to creating swap in btrfs for multi-disk so creating as seperate partition on single disk
swap_uuid=$(uuidgen)
mkswap -L swap -U $(uuidgen) /dev/nvme0n1p3

# MOUNTING 

# mount btrfs 
mount -o compress=zstd,subvol=root -U $btrfs_uuid /mnt
mkdir -p /mnt/{home,nix,persist,log}
mount -o compress=zstd,subvol=home -U $btrfs_uuid /mnt/home
mount -o compress=zstd,noatime,subvol=nix -U $btrfs_uuid /mnt/nix
mount -o compress=zstd,noatime,subvol=persist -U $btrfs_uuid /mnt/persist
mount -o compress=zstd,noatime,subvol=log -U $btrfs_uuid /mnt/log

# mount boot
mkdir -p /mnt/boot
mount -U $boot_uuid /mnt/boot

# mount swap
swapon -U $swap_uuid
```

**Comment by stephenandary** [comment]
unless we could convert device to "devices" and pass a list - that may be easy. I am new to nix though, so I will wait for your opinion.

**Comment by stephenandary** [comment]
Sorry about formatting, I forgot to turn it off again, but put rough thoughts into new commit.

**Comment by stephenandary** [comment]
@Mic92 I did my best to find a simple solution today, but I get stuck at mounting. I use uuid to mount my multidisk btrfs, and I am not sure how to work around that without rewriting existing code.

**Comment by stephenandary** [comment]
Closing PR as I am not using Disko right now so I won't be putting in more work, but if anything in this useful and needs discussion, please let me know.

**Comment by Mic92** [comment]
Pull requests welcome from other people. I don't use btrfs myself though.

**Pull request closed without merging**
