### PR TITLE
luks: rename extraArgs to extraFormatArgs, add extraOpenArgs

### PR DESCRIPTION
**Pull request by lheckemann**

### CODE REVIEW

**Comment by Lassulus** [comment]
ah, that was a breaking change, so we should comment it in BREAKING_CHANGES.md

**Comment by Lassulus** [comment]
which I have now done in https://github.com/nix-community/disko/pull/162

**Comment by Lassulus** [comment]
the luksOpenArgs are now only passed when first opening the device, not if booted later with nixos because they are not passed into the nixos config, is this something we want?

**Comment by lheckemann** [comment]
Ouch, that was absolutely not the plan :( it seems the NixOS module doesn't actually support passing arbitrary flags...

**Pull request merged**
