### PR TITLE
zfs_fs: support updating mountpoint properly

### PR DESCRIPTION
**Pull request by Enzime**
Use `zfs set -u` to update the `mountpoint` flag without mounting or unmounting the filesystem. This flag was added in OpenZFS 2.2.0, which was released October 2023.

The previous logic would not update `mountpoint` if `config.options` was empty or only contained `mountpoint`.

### CODE REVIEW

**Comment by Enzime** [comment]
@iFreilicht could you test if this change works on your system?

@Mic92 @Lassulus now that `_create` is idempotent, is it meant to be run online (with your disks already mounted) or offline?

**Comment by Mic92** [comment]
> @iFreilicht could you test if this change works on your system?
> 
> @Mic92 @Lassulus now that `_create` is idempotent, is it meant to be run online (with your disks already mounted) or offline?

It's meant to run from a installer or in-memory system that doesn't depend on the disks. However ideally it could also unmount disks as needed to perform the operation.

**Comment by iFreilicht** [comment]
> @iFreilicht could you test if this change works on your system?

Don't have access right now, will do next week. Feel free to ping me again if I didn't reply by next Wednesday.

**Comment by Enzime** [comment]
@iFreilicht out of curiosity, were you running the format script on an online machine or an offline one?

**Comment by iFreilicht** [comment]
I ran on an online system if by online you mean "already installed and with drives mounted".

**Comment by Enzime** [comment]
@Mic92 any idea why `make-disk-image` and `make-disk-image-impure` are failing in BuildBot? They succeed locally and there shouldn't be any changes in this PR compared to `master`

**Comment by Mic92** [comment]
@Enzime they seem to succeed now, but `.#checks.x86_64-linux.zfs-with-vdevs`

**Comment by Enzime** [comment]
@Mic92 yeah that check succeeds locally for me

**Comment by Enzime** [comment]
@Mic92 is there a way to trigger it to run again? I'm wondering if it's a flaky test

**Comment by Lassulus** [comment]
I can login into buildbot with github on the overview and then retrigger it, but maybe that's one of my undocumented superpowers I forgot about

**Comment by Mic92** [comment]
We just need to invite you to the nix-community org and then you can trigger rebuilds

**Comment by Mic92** [comment]
Invite sent.

**Comment by Enzime** [comment]
@mergify queue

**Pull request merged**
