### PR TITLE
Bcachefs fixes

### PR DESCRIPTION
**Pull request by Mic92**
bors merge

### CODE REVIEW

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
bors merge

**Comment by Lassulus** [comment]
still seems unhappy? not entirely happy with vendoring bcachefs in this repo. but if that's whats needed

**Comment by Lassulus** [comment]
not sure why it merged when https://github.com/nix-community/disko/pull/126/checks?check_run_id=10817692948 was failing? :D

**Comment by Mic92** [comment]
not sure either. I will investigate.

**Pull request merged**
