### PR TITLE
types,module,tests: run shellcheck on scripts before running them in NixOS tests

### PR DESCRIPTION
**Pull request by lilyinstarlight**
This is a draft because most generated scripts do not pass shellcheck and I want to make sure this approach is reasonable before fixing (or silencing) all of the little nits this finds

I had originally implemented it as a check run in the VM since that is a much simpler change, but I figured people may want to opt-in to having their scripts checked as they are generated (and also it is easier to get errors and fix that way when it's implemented as a checkPhase to the derivation rather than run in a VM way down the line)

(Also I may still change this approach -- I only wrote this in the last hour or two and tend to change my mind after a first implementation, but feedback is very welcome)

### CODE REVIEW

**Comment by lilyinstarlight** [comment]
Any thoughts on this @Lassulus and @Mic92?

I can start fixing (or silencing where appropriate) the reported shellcheck errors if both of you think this approach is reasonable for making it so that we have good shellcheck coverage even for generated scripts

**Comment by Mic92** [comment]
Yes. We should have shellcheck in our CI.

**Comment by Lassulus** [comment]
I will try to fix the remaining shellcheck errors and then we can merge this?

**Comment by Lassulus** [comment]
we got a small backwards incompatiblity, but I wanted to get rid of it anyways: all extraArgs are lists now

**Comment by lilyinstarlight** [comment]
> I will try to fix the remaining shellcheck errors and then we can merge this?

Awesome, thank you! :D

I'd intended to get to that at some point but this looks fabulous now

> we got a small backwards incompatiblity, but I wanted to get rid of it anyways: all extraArgs are lists now

That's probably for the best. Maybe we should start having a breaking changelog at some point?

**Comment by Lassulus** [comment]
> That's probably for the best. Maybe we should start having a breaking changelog at some point?

sounds like a good idea, should we add a `BREAKING_CHANGES.md` to the root of the repo? or do you have another idea?

**Comment by lilyinstarlight** [comment]
> sounds like a good idea, should we add a `BREAKING_CHANGES.md` to the root of the repo? or do you have another idea?

That sounds good enough to me. Or even just `CHANGES.md` would be fine, but I've no strong preference on name or method either way

**Comment by Mic92** [comment]
I also think CHANGES.md would be fine but don't have releases yet for sectioning.

**Comment by lilyinstarlight** [comment]
The breaking changes document looks fine enough for me, so is there anything else this PR is waiting on?

**Comment by Mic92** [comment]
bors merge

**Pull request merged**
